@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm9kb2xmbyBIIE9raW5vIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzU3NDYzODQ4P3Y9NCIsInN1YiI6ImY2YWEyODEyLTAyYTktNGFkNi1iM2Y1LTg5YTJjZWRkNmZlYiIsImlhdCI6MTY4NDM3Mzc2OCwiZXhwIjoxNjg2OTY1NzY4fQ.UuXwUWPDH4F-i4fnVm9SyvkPKwhRFO5hOz3cAXVo5m4

###
GET http://localhost:3333/memories
Authorization: Bearer {{token}}

###
GET http://localhost:3333/memories/c7e125a2-2295-4756-aadc-8522e8e568dc
Authorization: Bearer {{token}}

###
POST http://localhost:3333/memories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "test",
  "coverUrl": "https://github.com/diego3g.png",
  "isPublic": 1
}

###
PUT http://localhost:3333/memories/c7e125a2-2295-4756-aadc-8522e8e568dc
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "test update",
  "coverUrl": "https://github.com/rodolfoHOk.png",
  "isPublic": 1
}

###
DELETE http://localhost:3333/memories/60326518-a0ee-467e-8fa7-b968c8e13063
Authorization: Bearer {{token}}

###
POST http://localhost:3333/register
Content-Type: application/json

{
  "code": "69c2ff30a3151a841fae"
}

###
POST http://localhost:3333/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=multipartBoundary

--multipartBoundary
Content-Disposition: form-data; name="image"; filename="test.png"
Content-Type: image/png

< ./test.png
--multipartBoundary--

### Expect 400
POST http://localhost:3333/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=multipartBoundary

--multipartBoundary
Content-Disposition: form-data; name="text"; filename="test.txt"
Content-Type: text/plain

< ./test.txt
--multipartBoundary--
