@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm9kb2xmbyBIIE9raW5vIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzU3NDYzODQ4P3Y9NCIsInN1YiI6Ijc5OGU5Y2YzLTQ1MmEtNGExNi05NjdlLTQ3MTNjNWFlYjRhOSIsImlhdCI6MTY4NDkzMzQ5OSwiZXhwIjoxNjg3NTI1NDk5fQ.ZgB1DftOziSWcRGPdY3KPQdXTSe9Dwpbr5cAYcJKQ0k

###
GET http://localhost:3333/memories
Authorization: Bearer {{token}}

###
GET http://localhost:3333/memories/c7e125a2-2295-4756-aadc-8522e8e568dc
Authorization: Bearer {{token}}

###
POST http://localhost:3333/memories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "memoryDate": "2021-02-01T00:00:00.000Z",
  "content": "test",
  "coverUrl": "https://github.com/diego3g.png",
  "isPublic": 1
}

###
PUT http://localhost:3333/memories/83977ef0-2360-41c3-84dc-7c67711eea63
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "memoryDate": "2021-02-02T00:00:00.000Z",
  "content": "test update",
  "coverUrl": "https://github.com/rodolfoHOk.png",
  "isPublic": 1
}

###
DELETE http://localhost:3333/memories/83977ef0-2360-41c3-84dc-7c67711eea63
Authorization: Bearer {{token}}

###
POST http://localhost:3333/register
Content-Type: application/json

{
  "code": "69c2ff30a3151a841fae"
}

###
POST http://localhost:3333/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=multipartBoundary

--multipartBoundary
Content-Disposition: form-data; name="image"; filename="test.png"
Content-Type: image/png

< ./test.png
--multipartBoundary--

### Expect 400
POST http://localhost:3333/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=multipartBoundary

--multipartBoundary
Content-Disposition: form-data; name="text"; filename="test.txt"
Content-Type: text/plain

< ./test.txt
--multipartBoundary--
